# http://docs.travis-ci.com/user/languages/android/
language: android
jdk: oraclejdk7
notifications:
  email: true
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

android:
  components:
    # The BuildTools version used by your project
    - build-tools-24.0.1
    - extra

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - platform-tools

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-23

# Fix gradlew Permission denied issue
#before_install:
before_script:
 - chmod +x gradlew

# Emulator Management: Create, Start and Wait
#before_script:
#  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - adb wait-for-device
#  - adb shell input keyevent 82 &

script:
  # ./gradlew connectedAndroidTest
  ./gradlew clean assembleRelease